-- API abuse protection support for IntelliHire.
-- Run this once in Supabase SQL Editor.
--
-- This table is intentionally protected by RLS with no public policies.
-- The Next.js API routes should use SUPABASE_SERVICE_ROLE_KEY on the server
-- so only trusted server code can write/read API usage events.

create table if not exists public.api_usage_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  scope text not null,
  key_hash text not null,
  user_email text,
  route text,
  ip_hash text
);

create index if not exists api_usage_events_scope_key_created_at_idx
  on public.api_usage_events (scope, key_hash, created_at desc);

create index if not exists api_usage_events_created_at_idx
  on public.api_usage_events (created_at desc);

alter table public.api_usage_events enable row level security;

revoke all on table public.api_usage_events from anon, authenticated;
revoke all on sequence public.api_usage_events_id_seq from anon, authenticated;

grant all on table public.api_usage_events to service_role;
grant all on sequence public.api_usage_events_id_seq to service_role;

-- Optional cleanup you can run occasionally:
-- delete from public.api_usage_events where created_at < now() - interval '30 days';
