-- IntelliHire subscription, billing, and usage schema.
-- Run this after supabase_api_security.sql.

alter table public."Users"
  add column if not exists credits integer default 3,
  add column if not exists plan_key text default 'free',
  add column if not exists voice_minutes_remaining numeric default 15,
  add column if not exists billing_period_start timestamp with time zone default now(),
  add column if not exists billing_period_end timestamp with time zone default (now() + interval '30 days'),
  add column if not exists stripe_customer_id text,
  add column if not exists stripe_subscription_id text,
  add column if not exists subscription_status text default 'free';

update public."Users"
set
  credits = coalesce(credits, 3),
  plan_key = coalesce(plan_key, 'free'),
  voice_minutes_remaining = coalesce(voice_minutes_remaining, 15),
  billing_period_start = coalesce(billing_period_start, now()),
  billing_period_end = coalesce(billing_period_end, now() + interval '30 days'),
  subscription_status = coalesce(subscription_status, 'free');

create table if not exists public.plans (
  plan_key text primary key,
  name text not null,
  price_inr integer not null default 0,
  interval text not null default 'month',
  monthly_interview_credits integer not null,
  monthly_voice_minutes integer not null,
  stripe_price_id text,
  active boolean not null default true,
  created_at timestamp with time zone not null default now()
);

insert into public.plans (
  plan_key,
  name,
   price_inr,
  monthly_interview_credits,
  monthly_voice_minutes
) values
  ('free', 'Free', 0, 3, 15),
  ('starter', 'Starter', 499, 25, 100),
  ('pro', 'Pro', 1499, 100, 500)
on conflict (plan_key) do update set
  name = excluded.name,
  price_inr = excluded.price_inr,
  monthly_interview_credits = excluded.monthly_interview_credits,
  monthly_voice_minutes = excluded.monthly_voice_minutes,
  active = true;

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_email text not null,
  plan_key text not null references public.plans(plan_key),
  status text not null default 'inactive',
  stripe_customer_id text,
  stripe_subscription_id text unique,
  stripe_checkout_session_id text unique,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.subscriptions
  add column if not exists stripe_customer_id text,
  add column if not exists stripe_subscription_id text,
  add column if not exists stripe_checkout_session_id text,
  add column if not exists cancel_at_period_end boolean not null default false,
  add column if not exists updated_at timestamp with time zone not null default now();

create unique index if not exists subscriptions_stripe_subscription_id_key
  on public.subscriptions (stripe_subscription_id)
  where stripe_subscription_id is not null;

create unique index if not exists subscriptions_stripe_checkout_session_id_key
  on public.subscriptions (stripe_checkout_session_id)
  where stripe_checkout_session_id is not null;

create index if not exists subscriptions_user_email_idx
  on public.subscriptions (user_email);

create index if not exists subscriptions_status_idx
  on public.subscriptions (status);

create table if not exists public.usage_ledger (
  id bigint generated by default as identity primary key,
  user_email text not null,
  event_type text not null,
  quantity numeric not null default 1,
  plan_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now()
);

create index if not exists usage_ledger_user_email_created_at_idx
  on public.usage_ledger (user_email, created_at desc);

create index if not exists usage_ledger_event_type_idx
  on public.usage_ledger (event_type);

create table if not exists public.billing_events (
  id bigint generated by default as identity primary key,
  stripe_event_id text unique,
  event_type text not null,
  user_email text,
  processed boolean not null default false,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now()
);

alter table public.plans enable row level security;
alter table public.subscriptions enable row level security;
alter table public.usage_ledger enable row level security;
alter table public.billing_events enable row level security;
alter table public."Users" enable row level security;

drop policy if exists "Public can read active plans" on public.plans;
create policy "Public can read active plans"
  on public.plans
  for select
  using (active = true);

drop policy if exists "Users can read own subscriptions" on public.subscriptions;
create policy "Users can read own subscriptions"
  on public.subscriptions
  for select
  using (auth.jwt() ->> 'email' = user_email);

drop policy if exists "Users can read own usage" on public.usage_ledger;
create policy "Users can read own usage"
  on public.usage_ledger
  for select
  using (auth.jwt() ->> 'email' = user_email);

drop policy if exists "Users can read own profile" on public."Users";
create policy "Users can read own profile"
  on public."Users"
  for select
  using (auth.jwt() ->> 'email' = email);

revoke all on table public.billing_events from anon, authenticated;
revoke all on sequence public.billing_events_id_seq from anon, authenticated;

grant select on table public.plans to anon, authenticated;
grant select on table public.subscriptions to authenticated;
grant select on table public.usage_ledger to authenticated;
grant select on table public."Users" to authenticated;

grant all on table public.plans to service_role;
grant all on table public.subscriptions to service_role;
grant all on table public.usage_ledger to service_role;
grant all on table public.billing_events to service_role;
grant all on table public."Users" to service_role;

grant all on all sequences in schema public to service_role;
